### ISSUE TITLE
Define threshold for number of arguments

### ISSUE THREAD

**Issue by msberends** [gadenbuie/grkstyle#4]
Great package! You could perhaps let users set a threshold (e.g. with `options()`) so your transformations will only be effective if the threshold/minimum is met. The default could be 2. 

For example:
```r
df %>%
  group_by(var1, var2) %>%
  summarise(m = mean(n))

df %>%
  group_by(
    var1,
    var2,
    var3
  ) %>%
  summarise(m = mean(n))
```

**Comment by gadenbuie** [comment]
I like this idea in general, but the rule isn't based on number of arguments. The rule I've implemented is that if **any** function arguments appear on a new line, then **all** arguments should appear on a new line.

Another downside to the number of arguments approach is that some arguments are very long. Relatedly, styler doesn't style based on line length, so I think it's best for the author to choose between one-line or multi-line arguments by adding a newline anywhere in the argument list.

I'm closing the issue because I don't plan on implementing this, but I appreciate your feedback!

**Comment by msberends** [comment]
No problem!
